export const products = [
  {
    id: 1,
    category: "beef",
    categoryLabel: "Говядина",
    name: "Говядина (вырезка)",
    description:
      "Нежная вырезка высшего сорта, идеальна для стейков и медальонов",
    pricePerKg: 890,
    unit: "кг",
    minGrams: 100,
    stepGrams: 50,
    inStock: true,
    isPromo: false,
    promoBadge: null,
    image:
      "https://opttorg-horeca.ru/assets/images/catalog/meat/govyadina/vyrezka.jpg",
  },
  {
    id: 2,
    category: "beef",
    categoryLabel: "Говядина",
    name: "Говяжьи рёбра",
    description: "Сочные рёбра для запекания, тушения и барбекю",
    pricePerKg: 420,
    unit: "кг",
    minGrams: 500,
    stepGrams: 100,
    inStock: true,
    isPromo: true,
    promoBadge: "Хит недели",
    image:
      "https://moymyasnoy76.ru/upload/iblock/684/pkve9gjib5689vzf61ndv7hp1arhxxlr/4ca9eef0_c281_11e6_83fd_448a5b9d698b_755dd515_9126_11ea_a290_1c1b0d5c9ad6.jpg",
  },
  {
    id: 3,
    category: "beef",
    categoryLabel: "Говядина",
    name: "Говяжий фарш",
    description: "Свежемолотый фарш для котлет, бургеров и фаршированных блюд",
    pricePerKg: 380,
    unit: "кг",
    minGrams: 100,
    stepGrams: 50,
    inStock: true,
    isPromo: false,
    promoBadge: null,
    image:
      "https://e0.edimdoma.ru/data/ingredients/0000/1285/1285-ed4_wide.jpg?1533138141",
  },
  {
    id: 4,
    category: "beef",
    categoryLabel: "Говядина",
    name: "Антрекот (рибай)",
    description:
      "Мраморный стейк рибай с насыщенным вкусом и сочной структурой",
    pricePerKg: 1200,
    unit: "кг",
    minGrams: 200,
    stepGrams: 100,
    inStock: true,
    isPromo: false,
    promoBadge: null,
    image:
      "https://misafoods.eu/wp-content/uploads/2020/05/src.jpg",
  },
  {
    id: 5,
    category: "pork",
    categoryLabel: "Свинина",
    name: "Свиная шея",
    description: "Мягкое мясо с мраморными прожилками — идеально для шашлыка",
    pricePerKg: 320,
    unit: "кг",
    minGrams: 500,
    stepGrams: 100,
    inStock: true,
    isPromo: true,
    promoBadge: "Акция",
    image:
      "https://images.gastronom.ru/9WB69DmJ4EUUU54LSe45aHofN3PSbx0_ABHh8xrLemY/pr:product-preview-image/g:ce/rs:auto:0:0:0/L2Ntcy9hbGwtaW1hZ2VzLzFiZTY4OTc2LTRlMTYtNDIzNi04YzA1LTExODM4YWEzNzIxNy5qcGc.webp",
  },
  {
    id: 6,
    category: "pork",
    categoryLabel: "Свинина",
    name: "Свиные рёбрышки",
    description: "Нежные рёбрышки для тушения, запекания и гриля",
    pricePerKg: 280,
    unit: "кг",
    minGrams: 500,
    stepGrams: 100,
    inStock: true,
    isPromo: false,
    promoBadge: null,
    image:
      "https://fruitsparadise.ru/wp-content/uploads/2020/04/%D1%81%D0%B2%D0%B8%D0%BD%D1%8B%D0%B5-%D1%80%D0%B5%D0%B1%D1%80%D1%8B%D1%88%D0%BA%D0%B8.jpg",
  },
  {
    id: 7,
    category: "pork",
    categoryLabel: "Свинина",
    name: "Свиная грудинка",
    description: "Ароматная грудинка с прослойками сала для копчения и жарки",
    pricePerKg: 260,
    unit: "кг",
    minGrams: 300,
    stepGrams: 100,
    inStock: true,
    isPromo: false,
    promoBadge: null,
    image:
      "https://rdshop.ru/images/post/syraja-grudinka.jpg",
  },
  {
    id: 8,
    category: "pork",
    categoryLabel: "Свинина",
    name: "Свиная корейка",
    description: "Отборная корейка на кости для отбивных и запекания целиком",
    pricePerKg: 340,
    unit: "кг",
    minGrams: 500,
    stepGrams: 100,
    inStock: false,
    isPromo: false,
    promoBadge: null,
    image:
      "https://primemeat.ru/upload/iblock/97d/ko2q7xh3rkugoysb5sxkwpwvlgpgzaqi/koreyka_svinaya.jpg",
  },
  {
    id: 9,
    category: "chicken",
    categoryLabel: "Птица",
    name: "Куриная грудка",
    description: "Диетическое мясо без кожи и костей, богатое белком",
    pricePerKg: 220,
    unit: "кг",
    minGrams: 100,
    stepGrams: 50,
    inStock: true,
    isPromo: false,
    promoBadge: null,
    image:
      "https://images.unsplash.com/photo-1682991136736-a2b44623eeba?q=80&w=3131&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    id: 10,
    category: "chicken",
    categoryLabel: "Птица",
    name: "Куриные бёдра",
    description: "Сочные бёдра с косточкой, идеальны для запекания и тушения",
    pricePerKg: 180,
    unit: "кг",
    minGrams: 100,
    stepGrams: 50,
    inStock: true,
    isPromo: true,
    promoBadge: "Выгодно",
    image:
      "https://images.unsplash.com/photo-1759493321741-883fbf9f433c?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    id: 11,
    category: "chicken",
    categoryLabel: "Птица",
    name: "Индейка (филе)",
    description: "Нежное и постное филе индейки для здорового питания",
    pricePerKg: 390,
    unit: "кг",
    minGrams: 200,
    stepGrams: 100,
    inStock: true,
    isPromo: false,
    promoBadge: null,
    image:
      "https://images.unsplash.com/photo-1604503468506-a8da13d82791?q=80&w=987&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    id: 12,
    category: "chicken",
    categoryLabel: "Птица",
    name: "Утка целая",
    description:
      "Фермерская утка для праздничного запекания с хрустящей корочкой",
    pricePerKg: 480,
    unit: "кг",
    minGrams: 1000,
    stepGrams: 500,
    inStock: true,
    isPromo: false,
    promoBadge: null,
    image:
      "https://images.unsplash.com/photo-1672787380764-a603a9d4196d?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    id: 13,
    category: "sausage",
    categoryLabel: "Колбасы",
    name: "Докторская колбаса",
    description: "Классическая варёная колбаса по ГОСТу без лишних добавок",
    pricePerKg: 340,
    unit: "кг",
    minGrams: 100,
    stepGrams: 50,
    inStock: true,
    isPromo: false,
    promoBadge: null,
    image:
      "https://vodovoz.ru/upload/iblock/166/166cc8ae5d42970a4272645fbf9ee1b5.jpg",
  },
  {
    id: 14,
    category: "sausage",
    categoryLabel: "Колбасы",
    name: "Охотничьи колбаски",
    description: "Пикантные копчёные колбаски с пряностями, идеальны к пиву",
    pricePerKg: 560,
    unit: "кг",
    minGrams: 100,
    stepGrams: 50,
    inStock: true,
    isPromo: true,
    promoBadge: "Новинка",
    image:
      "https://images.unsplash.com/photo-1621800973389-768626d38a0c?q=80&w=2074&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    id: 15,
    category: "sausage",
    categoryLabel: "Колбасы",
    name: "Сервелат",
    description: "Полукопчёная колбаса с насыщенным вкусом и ароматом специй",
    pricePerKg: 620,
    unit: "кг",
    minGrams: 100,
    stepGrams: 50,
    inStock: true,
    isPromo: false,
    promoBadge: null,
    image:
      "https://images.unsplash.com/photo-1610970880754-708a4a004f42?q=80&w=1015&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    id: 16,
    category: "sausage",
    categoryLabel: "Колбасы",
    name: "Сосиски молочные",
    description:
      "Нежные молочные сосиски для быстрого завтрака и детского меню",
    pricePerKg: 290,
    unit: "кг",
    minGrams: 100,
    stepGrams: 50,
    inStock: false,
    isPromo: false,
    promoBadge: null,
    image:
      "https://images.unsplash.com/photo-1594909873098-0ed034675736?q=80&w=987&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
];
